# Generated by Django 5.2.7 on 2026-06-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_request_cr_no_request_location_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='admin_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='officer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='request',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded to TSP'), ('TSP_RESPONDED', 'TSP Responded'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='requeststatuslog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded to TSP'), ('TSP_RESPONDED', 'TSP Responded'), ('COMPLETED', 'Completed')], max_length=30),
        ),
    ]
