# Generated by Django 5.2.7 on 2026-06-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_request_admin_remarks_request_admin_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded to TSP'), ('TSP_RESPONDED', 'TSP Responded'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='requeststatuslog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded to TSP'), ('TSP_RESPONDED', 'TSP Responded'), ('COMPLETED', 'Completed')], max_length=30),
        ),
    ]
