# Generated by Django 5.2.7 on 2026-06-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_request_status_alter_requeststatuslog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='station_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
