# Generated by Django 5.2.15 on 2026-06-11 10:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_station_name_to_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='tspresponse',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tspresponse',
            name='additional_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tspresponse',
            name='circle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tspresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tspresponse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tspresponse',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='tspresponse',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tspresponse',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='tspresponse',
            name='subscriber_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tspresponse',
            name='tsp_provider',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tspresponse',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tspresponse',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tsp_responses', to='api.request'),
        ),
        migrations.AlterField(
            model_name='tspresponse',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
