# Generated by Django 5.2.7 on 2026-06-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tspresponse_activation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_absent_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='is_direct_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
