# Generated by Django 5.2.7 on 2026-06-12 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_request_is_absent_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='request',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='ticket_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tspprovider',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tspprovider',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded to TSP'), ('TSP_RESPONDED', 'TSP Response Received'), ('COMPLETED', 'Completed'), ('FORWARDED_OFFICER', 'Forwarded to Officer'), ('CLOSED', 'Closed')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='requeststatuslog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded to TSP'), ('TSP_RESPONDED', 'TSP Response Received'), ('COMPLETED', 'Completed'), ('FORWARDED_OFFICER', 'Forwarded to Officer'), ('CLOSED', 'Closed')], max_length=30),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received')], max_length=10)),
                ('operator', models.CharField(max_length=50)),
                ('tsp_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='api.request')),
            ],
        ),
    ]
