# Generated by Django 5.2.7 on 2026-06-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_request_message_request_subject_request_ticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded to TSP'), ('TSP_RESPONDED', 'TSP Response Received'), ('COMPLETED', 'Forwarded to Officer'), ('CLOSED', 'Closed')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='requeststatuslog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded to TSP'), ('TSP_RESPONDED', 'TSP Response Received'), ('COMPLETED', 'Forwarded to Officer'), ('CLOSED', 'Closed')], max_length=30),
        ),
    ]
