# Generated by Django 5.2.7 on 2026-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_request_status_alter_requeststatuslog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tspprovider',
            name='inbound_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
