# Generated by Django 5.2.7 on 2026-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_inbound_number_to_tsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tspprovider',
            name='inbound_number',
            field=models.CharField(blank=True, default='7353224350', max_length=15),
        ),
    ]
