# Generated by Django 5.2.7 on 2026-06-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tspprovider_inbound_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsetting',
            name='bypass_daily_limit',
            field=models.BooleanField(default=False),
        ),
    ]
