# Generated by Django 5.2.7 on 2026-06-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_permissionsetting_bypass_daily_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminForwardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarded_message', models.TextField(blank=True, default='')),
                ('forwarded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Forwarded', max_length=30)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_by_admin', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_records', to='api.request')),
                ('tsp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_to_tsp', to='api.tspprovider')),
            ],
        ),
    ]
