# Generated by Django 5.2.7 on 2026-06-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_adminforwardrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsetting',
            name='bypass_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tspprovider',
            name='inbound_number',
            field=models.CharField(blank=True, default='9844281875', max_length=15),
        ),
    ]
