# Generated by Django 5.2.7 on 2026-06-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_permissionsetting_bypass_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsetting',
            name='bypass_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permissionsetting',
            name='extra_requests_limit',
            field=models.IntegerField(default=0),
        ),
    ]
