# Generated by Django 5.2.7 on 2026-06-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_logindetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TspSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsp_name', models.CharField(max_length=100, unique=True)),
                ('forward_number', models.CharField(blank=True, default='', max_length=15)),
                ('sms_template', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tsp_settings',
            },
        ),
    ]
