# Generated by Django 5.2.15 on 2026-06-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tspsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tspprovider',
            name='sms_template',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
