# Generated by Django 5.2.7 on 2026-06-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_tspprovider_sms_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tspprovider',
            name='sms_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tspsetting',
            name='sms_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
