# Generated by Django 5.2.7 on 2026-06-23 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_tspprovider_sms_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tspsetting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
