# Generated by Django 5.2.15 on 2026-06-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_tspsetting_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='actlog_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['officer', '-created_at'], name='req_officer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['tsp', '-created_at'], name='req_tsp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='req_status_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['user', '-created_at'], name='notif_user_created_idx'),
        ),
    ]
