# Generated by Django 5.2.15 on 2026-06-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_activitylog_actlog_timestamp_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='station_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
